
package com.xsrw.wms.webservice.cn.com.shenhuagroup.xstlzhcc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.xsrw.wms.webservice.com.sap.document.sap.rfc.functions.ObjectFactory;
import com.xsrw.wms.webservice.com.sap.document.sap.rfc.functions.ZWMXSJWHCZCSQXX;
import com.xsrw.wms.webservice.com.sap.document.sap.rfc.functions.ZWMXSJWHCZCSQXXResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_03KL8_XSTLZHCC2ERP_HCZCSQXX", targetNamespace = "http://www.shenhuagroup.com.cn/XSTLZHCC")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SI03KL8XSTLZHCC2ERPHCZCSQXX {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.sap.document.sap.rfc.functions.ZWMXSJWHCZCSQXXResponse
     */
    @WebMethod(operationName = "SI_03KL8_XSTLZHCC2ERP_HCZCSQXX", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "Z_WM_XSJW_HCZCSQXX.Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
    public ZWMXSJWHCZCSQXXResponse si03KL8XSTLZHCC2ERPHCZCSQXX(
        @WebParam(name = "Z_WM_XSJW_HCZCSQXX", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
        ZWMXSJWHCZCSQXX parameters);

}
