package com.xsrw.wms.webservice.cn.com.shenhuagroup.xstlzhcc;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.xsrw.wms.webservice.util.WebServiceUtils;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "SI_03KM2_XSTLZHCC2ERP_RECEIVEService", targetNamespace = "http://www.shenhuagroup.com.cn/XSTLZHCC", wsdlLocation = "file:/C:/Users/49176/Desktop/ww/SI_03KM2_XSTLZHCC2ERP_RECEIVE_P.wsdl")
public class SI03KM2XSTLZHCC2ERPRECEIVEService
    extends Service
{

    private final static URL SI03KM2XSTLZHCC2ERPRECEIVESERVICE_WSDL_LOCATION;
    private final static WebServiceException SI03KM2XSTLZHCC2ERPRECEIVESERVICE_EXCEPTION;
    private final static QName SI03KM2XSTLZHCC2ERPRECEIVESERVICE_QNAME = new QName("http://www.shenhuagroup.com.cn/XSTLZHCC", "SI_03KM2_XSTLZHCC2ERP_RECEIVEService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            String wsdlPath = "file:/D:/xsrw/wsdl/SI_03KM2_XSTLZHCC2ERP_RECEIVE_P.wsdl";
            url = new URL(wsdlPath);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SI03KM2XSTLZHCC2ERPRECEIVESERVICE_WSDL_LOCATION = url;
        SI03KM2XSTLZHCC2ERPRECEIVESERVICE_EXCEPTION = e;
    }

    public SI03KM2XSTLZHCC2ERPRECEIVEService() {
        super(__getWsdlLocation(), SI03KM2XSTLZHCC2ERPRECEIVESERVICE_QNAME);
    }

    public SI03KM2XSTLZHCC2ERPRECEIVEService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SI03KM2XSTLZHCC2ERPRECEIVESERVICE_QNAME, features);
    }

    public SI03KM2XSTLZHCC2ERPRECEIVEService(URL wsdlLocation) {
        super(wsdlLocation, SI03KM2XSTLZHCC2ERPRECEIVESERVICE_QNAME);
    }

    public SI03KM2XSTLZHCC2ERPRECEIVEService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SI03KM2XSTLZHCC2ERPRECEIVESERVICE_QNAME, features);
    }

    public SI03KM2XSTLZHCC2ERPRECEIVEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SI03KM2XSTLZHCC2ERPRECEIVEService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SI03KM2XSTLZHCC2ERPRECEIVE
     */
    @WebEndpoint(name = "SI_03KM2_XSTLZHCC2ERP_RECEIVEPort")
    public SI03KM2XSTLZHCC2ERPRECEIVE getSI03KM2XSTLZHCC2ERPRECEIVEPort() {
        return super.getPort(new QName("http://www.shenhuagroup.com.cn/XSTLZHCC", "SI_03KM2_XSTLZHCC2ERP_RECEIVEPort"), SI03KM2XSTLZHCC2ERPRECEIVE.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SI03KM2XSTLZHCC2ERPRECEIVE
     */
    @WebEndpoint(name = "SI_03KM2_XSTLZHCC2ERP_RECEIVEPort")
    public SI03KM2XSTLZHCC2ERPRECEIVE getSI03KM2XSTLZHCC2ERPRECEIVEPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.shenhuagroup.com.cn/XSTLZHCC", "SI_03KM2_XSTLZHCC2ERP_RECEIVEPort"), SI03KM2XSTLZHCC2ERPRECEIVE.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SI03KM2XSTLZHCC2ERPRECEIVESERVICE_EXCEPTION!= null) {
            throw SI03KM2XSTLZHCC2ERPRECEIVESERVICE_EXCEPTION;
        }
        return SI03KM2XSTLZHCC2ERPRECEIVESERVICE_WSDL_LOCATION;
    }

}
