package com.xsrw.wms.webservice.cn.com.shenhuagroup.xstlzhcc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.xsrw.wms.webservice.com.sap.document.sap.rfc.functions.ObjectFactory;
import com.xsrw.wms.webservice.com.sap.document.sap.rfc.functions.ZWMXSJWHCCWYDXX;
import com.xsrw.wms.webservice.com.sap.document.sap.rfc.functions.ZWMXSJWHCCWYDXXResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "SI_03KL9_XSTLZHCC2ERP_HCCWYDXX", targetNamespace = "http://www.shenhuagroup.com.cn/XSTLZHCC")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SI03KL9XSTLZHCC2ERPHCCWYDXX {


    /**
     *
     * @param parameters
     * @return
     *     returns com.sap.document.sap.rfc.functions.ZWMXSJWHCCWYDXXResponse
     */
    @WebMethod(operationName = "SI_03KL9_XSTLZHCC2ERP_HCCWYDXX", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "Z_WM_XSJW_HCCWYDXX.Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
    public ZWMXSJWHCCWYDXXResponse si03KL9XSTLZHCC2ERPHCCWYDXX(
        @WebParam(name = "Z_WM_XSJW_HCCWYDXX", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
        ZWMXSJWHCCWYDXX parameters);

}
