package com.xsrw.wms.webservice.cn.com.shenhuagroup.xstlzhcc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.xsrw.wms.webservice.com.sap.document.sap.rfc.functions.ObjectFactory;
import com.xsrw.wms.webservice.com.sap.document.sap.rfc.functions.ZWMXSJW2ERPRECEIVE;
import com.xsrw.wms.webservice.com.sap.document.sap.rfc.functions.ZWMXSJW2ERPRECEIVEResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_03KM2_XSTLZHCC2ERP_RECEIVE", targetNamespace = "http://www.shenhuagroup.com.cn/XSTLZHCC")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SI03KM2XSTLZHCC2ERPRECEIVE {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.sap.document.sap.rfc.functions.ZWMXSJW2ERPRECEIVEResponse
     */
    @WebMethod(operationName = "SI_03KM2_XSTLZHCC2ERP_RECEIVE", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "Z_WM_XSJW2ERP_RECEIVE.Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
    public ZWMXSJW2ERPRECEIVEResponse si03KM2XSTLZHCC2ERPRECEIVE(
        @WebParam(name = "Z_WM_XSJW2ERP_RECEIVE", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
        ZWMXSJW2ERPRECEIVE parameters);

}
