package com.xsrw.wms.webservice.cn.com.shenhuagroup.xstlzhcc;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.xsrw.wms.webservice.util.WebServiceUtils;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "SI_03KL9_XSTLZHCC2ERP_HCCWYDXXService", targetNamespace = "http://www.shenhuagroup.com.cn/XSTLZHCC", wsdlLocation = "file:/C:/Users/49176/Desktop/ww/SI_03KL9_XSTLZHCC2ERP_HCCWYDXX_P.wsdl")
public class SI03KL9XSTLZHCC2ERPHCCWYDXXService
    extends Service
{

    private final static URL SI03KL9XSTLZHCC2ERPHCCWYDXXSERVICE_WSDL_LOCATION;
    private final static WebServiceException SI03KL9XSTLZHCC2ERPHCCWYDXXSERVICE_EXCEPTION;
    private final static QName SI03KL9XSTLZHCC2ERPHCCWYDXXSERVICE_QNAME = new QName("http://www.shenhuagroup.com.cn/XSTLZHCC", "SI_03KL9_XSTLZHCC2ERP_HCCWYDXXService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            String wsdlPath = WebServiceUtils.class.getClassLoader().getResource("wsdl/SI_03KL9_XSTLZHCC2ERP_HCCWYDXX_P.wsdl").getPath();
            url = new URL("file:"+wsdlPath);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SI03KL9XSTLZHCC2ERPHCCWYDXXSERVICE_WSDL_LOCATION = url;
        SI03KL9XSTLZHCC2ERPHCCWYDXXSERVICE_EXCEPTION = e;
    }

    public SI03KL9XSTLZHCC2ERPHCCWYDXXService() {
        super(__getWsdlLocation(), SI03KL9XSTLZHCC2ERPHCCWYDXXSERVICE_QNAME);
    }

    public SI03KL9XSTLZHCC2ERPHCCWYDXXService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SI03KL9XSTLZHCC2ERPHCCWYDXXSERVICE_QNAME, features);
    }

    public SI03KL9XSTLZHCC2ERPHCCWYDXXService(URL wsdlLocation) {
        super(wsdlLocation, SI03KL9XSTLZHCC2ERPHCCWYDXXSERVICE_QNAME);
    }

    public SI03KL9XSTLZHCC2ERPHCCWYDXXService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SI03KL9XSTLZHCC2ERPHCCWYDXXSERVICE_QNAME, features);
    }

    public SI03KL9XSTLZHCC2ERPHCCWYDXXService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SI03KL9XSTLZHCC2ERPHCCWYDXXService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SI03KL9XSTLZHCC2ERPHCCWYDXX
     */
    @WebEndpoint(name = "SI_03KL9_XSTLZHCC2ERP_HCCWYDXXPort")
    public SI03KL9XSTLZHCC2ERPHCCWYDXX getSI03KL9XSTLZHCC2ERPHCCWYDXXPort() {
        return super.getPort(new QName("http://www.shenhuagroup.com.cn/XSTLZHCC", "SI_03KL9_XSTLZHCC2ERP_HCCWYDXXPort"), SI03KL9XSTLZHCC2ERPHCCWYDXX.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SI03KL9XSTLZHCC2ERPHCCWYDXX
     */
    @WebEndpoint(name = "SI_03KL9_XSTLZHCC2ERP_HCCWYDXXPort")
    public SI03KL9XSTLZHCC2ERPHCCWYDXX getSI03KL9XSTLZHCC2ERPHCCWYDXXPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.shenhuagroup.com.cn/XSTLZHCC", "SI_03KL9_XSTLZHCC2ERP_HCCWYDXXPort"), SI03KL9XSTLZHCC2ERPHCCWYDXX.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SI03KL9XSTLZHCC2ERPHCCWYDXXSERVICE_EXCEPTION!= null) {
            throw SI03KL9XSTLZHCC2ERPHCCWYDXXSERVICE_EXCEPTION;
        }
        return SI03KL9XSTLZHCC2ERPHCCWYDXXSERVICE_WSDL_LOCATION;
    }

}
